### ISSUE TITLE
import MultiScaleDeformableAttention as MSDA Module not found error

### ISSUE THREAD

**Issue by iremsusavas** [PJLallen/OSFormer#11]
Hello, I have followed all the steps mentioned, and when i want to perform training it gives me the following error : import MultiScaleDeformableAttention as MSDA Module not found

Anyone faced this issue, or any possible suggestions would be really appreciated

**Comment by Singerone** [comment]
OSFormer/adet/modeling/ops/make.sh
Maybe you need try "bash make.sh " before debugging code

**Comment by PJLallen** [comment]
Hello, did you execute the command "python setup.py build develop" in the virtual environment?  We have integrated it in ‘setup.py’, please see:
```
    sources = [os.path.join(extensions_dir, s) for s in sources]
    include_dirs = [extensions_dir]
    ext_modules = [
        extension(
            "MultiScaleDeformableAttention",
            sources,
            include_dirs=include_dirs,
            define_macros=define_macros,
            extra_compile_args=extra_compile_args,
        )
    ]
    return ext_modules
```
In addition, you can also solve it by executing ”OSFormer/adet/modeling/ops/make.sh“ directly in the virtual environment.
