### ISSUE TITLE
Multi class segmentation

### ISSUE THREAD

**Issue by iremsusavas** [PJLallen/OSFormer#13]
Is it possible to segment multiple classes instead of just one class?

**Comment by PJLallen** [comment]
Hi, you can use our OSFormer to segment any number of classes. First, you should know the total number of classes in your dataset. Then, you just need to change the initial parameter "NUM_CLASSES" in accordance with your project. Thanks.

**Comment by OuyKai** [comment]
configs/Base-CIS.yaml

NUM_CLASSES
