### ISSUE TITLE
NotImplementedError: Cuda is not availabel

### ISSUE THREAD

**Issue by github-eliviate** [PJLallen/OSFormer#16]
![image](https://github.com/PJLallen/OSFormer/assets/14120941/0ec7ea05-5e56-4e20-ab76-2a50ba1f1fdd)
setup.py中需要使用CUDA_HOME，否则报错
![image](https://github.com/PJLallen/OSFormer/assets/14120941/aa5cfb96-8dc9-4841-9040-3b6a629b31c7)

但是readme中，只让安装了cudatoolkit
请问CUDA是否仍需要安装

**Comment by JAYCHOU2020** [comment]
请问您解决问题了吗，
我安装的有cuda为什么还是会报这个错误呢

**Comment by github-eliviate** [comment]
解决了，安装的英伟达的cudatoolkit，虚拟环境中的cuda包少东西
