### ISSUE TITLE
code environment 

### ISSUE THREAD

**Issue by another-u** [PJLallen/OSFormer#5]
Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. 
We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?

**Comment by Patrickctyyx** [comment]
Did you run the code with gpu? The deformable attention is based on gpu and not support cpu yet.

**Comment by another-u** [comment]
The computer I use is RTX3090.

**Comment by Patrickctyyx** [comment]
It seems that some lib is missing, maybe try https://github.com/theimpostor/termux-vim-ycm/issues/1 and install `libcrypt-dev`？

**Comment by PJLallen** [comment]
> Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?

The version of our torch is 1.9.0, you can use this cmmand to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f \
  https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”.

**Comment by another-u** [comment]
> > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> 
> The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).

Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.

**Comment by PJLallen** [comment]
> > > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> > 
> > 
> > The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).
> 
> Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.

Our system is Ubuntu 18.04 with a single RTX3090. We have tested repeatedly, and there is no problem as you mentioned.

**Comment by another-u** [comment]
> > > > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> > > 
> > > 
> > > The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).
> > 
> > 
> > Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.
> 
> Our system is Ubuntu 18.04 with a single RTX3090. We have tested repeatedly, and there is no problem as you mentioned.

Thank you! It has been solved. I updated g++and finally successfully installed the code environment.

**Comment by marcodavidg** [comment]
I've tried to setup the environment for some days now with no luck. I already have the same torch, torchvision, cudatoolkit and detectron2 versions. I am getting this error now when I try to execute the demo.py, can you maybe know what is wrong with my process? Thanks for any answer.

`ImportError: cannot import name 'register_model' from 'timm.models.registry' `

The full thing is:

``Traceback (most recent call last):
  File "demo/demo.py", line 13, in <module>
    from predictor import VisualizationDemo
  File "/home/lami/Documents/OSFormer-main/demo/predictor.py", line 15, in <module>
    from adet.utils.visualizer import TextVisualizer
  File "/home/lami/Documents/OSFormer-main/adet/__init__.py", line 1, in <module>
    from adet import modeling
  File "/home/lami/Documents/OSFormer-main/adet/modeling/__init__.py", line 1, in <module>
    from .backbone import build_fcos_resnet_fpn_backbone
  File "/home/lami/Documents/OSFormer-main/adet/modeling/backbone/__init__.py", line 5, in <module>
    from .pvt_v2 import build_pvt_v2_b2_li, build_pvt_v2_fpn_b2_li
  File "/home/lami/Documents/OSFormer-main/adet/modeling/backbone/pvt_v2.py", line 6, in <module>
    from timm.models.registry import register_model
ImportError: cannot import name 'register_model' from 'timm.models.registry' ``

**Comment by JAYCHOU2020** [comment]
> > > > > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> > > > 
> > > > 
> > > > The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).
> > > 
> > > 
> > > Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.
> > 
> > 
> > Our system is Ubuntu 18.04 with a single RTX3090. We have tested repeatedly, and there is no problem as you mentioned.
> 
> Thank you! It has been solved. I updated g++and finally successfully installed the code environment.

What is your version of g++

**Comment by JAYCHOU2020** [comment]
> > > > > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> > > > 
> > > > 
> > > > The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).
> > > 
> > > 
> > > Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.
> > 
> > 
> > Our system is Ubuntu 18.04 with a single RTX3090. We have tested repeatedly, and there is no problem as you mentioned.
> 
> Thank you! It has been solved. I updated g++and finally successfully installed the code environment.



> > > > > Hello, I want to ask about the code environment. I installed the code environment according to the readme file provided by you, but I found that when I performed the last step of python setup.py build develop, a RuntimeError: Error compiling objects for extension appears, and we find that the cause of compilation terminated is false error: crypt h: No such file or directory. We tried many methods but failed to solve them. What we can confirm is that the versions of our torch, torch vision and detecton2 are the same as what you mentioned. I want to ask how to solve this problem?
> > > > 
> > > > 
> > > > The version of our torch is 1.9.0, you can use this command to install: "conda install pytorch==1.9.0 torchvision cudatoolkit=11.1 -c pytorch -c nvidia". For Detectron2, the corresponding version is: “python -m pip install detectron2 -f [https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html”](https://dl.fbaipublicfiles.com/detectron2/wheels/cu111/torch1.9/index.html%E2%80%9D).
> > > 
> > > 
> > > Yes, our torch, torchvision and cudatoolkit are the same as yours, and the detectron2 version is the same, but we execute the last step of python setup.py build develop. This error occurs.
> > 
> > 
> > Our system is Ubuntu 18.04 with a single RTX3090. We have tested repeatedly, and there is no problem as you mentioned.
> 
> Thank you! It has been solved. I updated g++and finally successfully installed the code environment.

can you tell me the right version of gcc
