### ISSUE TITLE
How to convert customer dataset formats

### ISSUE THREAD

**Issue by updatelse** [PJLallen/OSFormer#6]
Hello, I want to train my own dataset based on OSFormer code. 
At present, I have 1500 images and 1500 corresponding annotated json files. 
How should I organize a data set in COCO format next? Could you please open source the scripts for organizing data sets?
![image](https://user-images.githubusercontent.com/72791802/199429421-0e4cf3f0-51ea-4f66-855b-40a089675768.png)

 I want to generate the two json file.
![image](https://user-images.githubusercontent.com/72791802/199429663-b990be6e-e75d-4068-90c5-4a83a6dc5349.png)

**Comment by PJLallen** [comment]
COCO-style json files are easily produced, referring to https://cocodataset.org/#format-data.
