### ISSUE TITLE
Result in AP50(69) of COD10k-Test is lower than paper(71.1)

### ISSUE THREAD

**Issue by orayel** [PJLallen/OSFormer#9]
HI, thanks for your great work in CIS. But i got some question in performance of the ap50 in COD10K-Test. First, i download the weights of CIS_R50 ,and then use the config of CIS_R50.yaml to eval the result in COD10K_Test by using train_net.py and open --eval-only . But i got the performance(69) lower than the value in paper(71.1). So what's the wrong ? Waiting for your reply!

**Comment by Patrickctyyx** [comment]
Hi, orayel. I've tested the weight in a new environment, which is 3060Ti with CUDA 11.3.1, python 3.8, pytorch 1.10, and detectron2 0.6. The AP50 result is 71.125.
You can change your environment and see if the results are different.

**Comment by orayel** [comment]
> Hi, orayel. I've tested the weight in a new environment, which is 3060Ti with CUDA 11.3.1, python 3.8, pytorch 1.10, and detectron2 0.6. The AP50 result is 71.125. You can change your environment and see if the results are different.

Thanks for your reply. I will try different environment latter. But  will result be different between different environment by using the same checkpoint?
